import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { ShieldCheck, AlertTriangle, Lock } from 'lucide-react';
import { AYKENOS_EVIDENCE_CHAIN } from '@ayatlas/authority-resolver';
export const EvidenceExplorer = ({ headSha }) => {
    const [selectedStep, setSelectedStep] = useState(AYKENOS_EVIDENCE_CHAIN[3]); // Default: Validator Output
    return (_jsxs("div", { className: "p-6 max-w-7xl mx-auto space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-xl font-bold text-slate-100 flex items-center space-x-2", children: [_jsx(ShieldCheck, { className: "h-5 w-5 text-cyan-400" }), _jsx("span", { children: "Evidence Intelligence & Governance Boundary" })] }), _jsx("p", { className: "text-xs text-slate-400 mt-1", children: "Visualizing the strict constitutional boundary separating raw execution output, validator output, exact-subject binding, and accepted evidence." })] }), _jsxs("div", { className: "flex items-center space-x-2 bg-amber-500/10 px-3 py-1.5 rounded-xl border border-amber-500/20 text-xs font-mono text-amber-300", children: [_jsx(AlertTriangle, { className: "h-4 w-4 text-amber-400" }), _jsx("span", { children: "INVARIANT: Validator PASS != Accepted Evidence" })] })] }), _jsxs("div", { className: "glass-panel p-6 border-cyan-500/30 space-y-4", children: [_jsx("h3", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider", children: "Sequential Evidence & Authority Verification Pipeline" }), _jsx("div", { className: "grid grid-cols-4 gap-3", children: AYKENOS_EVIDENCE_CHAIN.map((step, idx) => {
                            const isSelected = selectedStep.id === step.id;
                            const isAcceptedStep = step.stage === 'ACCEPTED_EVIDENCE';
                            return (_jsxs("div", { onClick: () => setSelectedStep(step), className: `p-4 rounded-xl border cursor-pointer transition-all duration-200 relative ${isSelected
                                    ? 'border-cyan-500/60 bg-slate-900/90 shadow-cyan-500/10'
                                    : isAcceptedStep
                                        ? 'border-emerald-500/30 bg-emerald-500/5 hover:border-emerald-500/50'
                                        : 'border-slate-800 bg-slate-950/60 hover:border-slate-700'}`, children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-xs font-mono text-cyan-400 font-semibold", children: step.stepName }), step.isAuthorityGranted ? (_jsx("span", { className: "text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 font-bold", children: "AUTHORITY RATIFIED" })) : (_jsx("span", { className: "text-[10px] font-mono px-2 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/30", children: "NO AUTHORITY" }))] }), _jsx("div", { className: "text-xs text-slate-300 line-clamp-2", children: step.description })] }, step.id));
                        }) })] }), _jsxs("div", { className: "glass-panel p-6 border-slate-800 space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-slate-800 pb-3", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs font-mono text-cyan-400 uppercase tracking-wider font-semibold", children: "Evidence Stage Deep Inspection" }), _jsx("h3", { className: "text-lg font-bold text-slate-100", children: selectedStep.stepName })] }), _jsxs("span", { className: "text-xs font-mono px-3 py-1 rounded-full bg-slate-900 border border-slate-800 text-slate-300", children: ["Stage: ", selectedStep.stage] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider mb-2", children: "Description" }), _jsx("p", { className: "text-xs text-slate-300 bg-slate-950/80 p-3.5 rounded-lg border border-slate-800 leading-relaxed", children: selectedStep.description })] }), _jsxs("div", { children: [_jsxs("h4", { className: "text-xs font-bold text-amber-400 uppercase tracking-wider mb-2 flex items-center space-x-1", children: [_jsx(Lock, { className: "h-3.5 w-3.5 text-amber-400" }), _jsx("span", { children: "Constitutional Governance Constraint" })] }), _jsx("p", { className: "text-xs text-amber-300 bg-amber-500/10 p-3.5 rounded-lg border border-amber-500/20 leading-relaxed font-mono", children: selectedStep.governanceConstraint })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider mb-2", children: "Associated Repository Code Paths" }), _jsx("div", { className: "flex space-x-2", children: selectedStep.codePaths.map((p, idx) => (_jsx("span", { className: "text-xs font-mono text-cyan-400 bg-slate-950 px-3 py-1.5 rounded-lg border border-slate-800", children: p }, idx))) })] })] })] }));
};
//# sourceMappingURL=EvidenceExplorer.js.map