import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Network, ArrowRight } from 'lucide-react';
import { GovernanceKnowledgeGraphEngine } from '@ayatlas/graph-engine';
export const GovernanceKnowledgeGraph = ({ headSha }) => {
    const [engine] = useState(() => new GovernanceKnowledgeGraphEngine());
    const [selectedNodeId, setSelectedNodeId] = useState('phase-24');
    const nodes = engine.getAllNodes();
    const edges = engine.getAllEdges();
    const neighborhood = engine.getNeighborhood(selectedNodeId);
    return (_jsxs("div", { className: "p-6 max-w-7xl mx-auto space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-xl font-bold text-slate-100 flex items-center space-x-2", children: [_jsx(Network, { className: "h-5 w-5 text-cyan-400" }), _jsx("span", { children: "Interactive Governance Knowledge Graph" })] }), _jsx("p", { className: "text-xs text-slate-400 mt-1", children: "Cross-document reasoning engine connecting constitutional invariants, phase decisions, ABI boundaries, and evidence chains." })] }), _jsxs("div", { className: "flex items-center space-x-2 bg-slate-900 p-2 rounded-xl border border-slate-800 text-xs font-mono", children: [_jsx("span", { className: "text-slate-400", children: "Canonical SHA:" }), _jsx("span", { className: "text-cyan-400 font-bold", children: headSha.slice(0, 8) })] })] }), _jsxs("div", { className: "grid grid-cols-3 gap-6", children: [_jsxs("div", { className: "col-span-2 space-y-4", children: [_jsxs("div", { className: "glass-panel p-6 border-cyan-500/30 space-y-4", children: [_jsx("h3", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider", children: "Constitutional Knowledge Graph Topology Nodes" }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: nodes.map((node) => {
                                            const isSelected = node.id === selectedNodeId;
                                            return (_jsxs("div", { onClick: () => setSelectedNodeId(node.id), className: `p-4 rounded-xl border cursor-pointer transition-all duration-200 ${isSelected
                                                    ? 'border-cyan-500/70 bg-slate-900/90 shadow-lg shadow-cyan-500/10'
                                                    : 'border-slate-800 bg-slate-950/60 hover:border-slate-700'}`, children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("span", { className: "text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 font-semibold", children: node.domain }), _jsx("span", { className: "text-[10px] font-mono text-slate-400", children: node.authorityClass })] }), _jsx("h4", { className: "text-xs font-bold text-slate-100 mb-1", children: node.label }), _jsx("p", { className: "text-[11px] text-slate-400 line-clamp-2", children: node.description })] }, node.id));
                                        }) })] }), _jsxs("div", { className: "glass-panel p-5 border-slate-800 space-y-3", children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider", children: "System Relationships & Governance Invariants" }), _jsx("div", { className: "space-y-2", children: edges.map((edge) => (_jsxs("div", { className: "bg-slate-950/80 p-3 rounded-lg border border-slate-800 text-xs font-mono flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-2 text-cyan-300", children: [_jsx("span", { className: "font-semibold", children: edge.sourceId }), _jsx("span", { className: "text-amber-400 px-2 py-0.5 rounded bg-amber-500/10 border border-amber-500/20 text-[10px]", children: edge.relation }), _jsx("span", { className: "font-semibold", children: edge.targetId })] }), _jsx("span", { className: "text-[11px] text-slate-400", children: edge.description })] }, edge.id))) })] })] }), _jsx("div", { className: "space-y-4", children: neighborhood && (_jsxs("div", { className: "glass-panel p-6 border-cyan-500/30 space-y-4", children: [_jsxs("div", { className: "border-b border-slate-800 pb-3", children: [_jsx("span", { className: "text-xs font-mono text-cyan-400 uppercase tracking-wider font-semibold", children: "Cross-Document Neighborhood" }), _jsx("h3", { className: "text-base font-bold text-slate-100 mt-1", children: neighborhood.targetNode.label })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider mb-1", children: "Domain & Authority" }), _jsxs("div", { className: "flex space-x-2 text-xs font-mono", children: [_jsx("span", { className: "px-2 py-1 rounded bg-slate-900 border border-slate-800 text-cyan-300", children: neighborhood.targetNode.domain }), _jsx("span", { className: "px-2 py-1 rounded bg-slate-900 border border-slate-800 text-emerald-400", children: neighborhood.targetNode.authorityClass })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider mb-1", children: "Node Description" }), _jsx("p", { className: "text-xs text-slate-300 bg-slate-950/60 p-3 rounded-lg border border-slate-800 leading-relaxed", children: neighborhood.targetNode.description })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider mb-2", children: "Connected Governance Nodes" }), _jsx("div", { className: "space-y-2", children: neighborhood.connectedNodes.map((n) => (_jsxs("div", { onClick: () => setSelectedNodeId(n.id), className: "bg-slate-950 p-2.5 rounded-lg border border-slate-800 text-xs font-mono cursor-pointer hover:border-cyan-500/40 flex items-center justify-between", children: [_jsx("span", { className: "text-cyan-300 font-semibold", children: n.label }), _jsx(ArrowRight, { className: "h-3 w-3 text-slate-500" })] }, n.id))) })] })] })) })] })] }));
};
//# sourceMappingURL=GovernanceKnowledgeGraph.js.map