import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Activity, ShieldCheck, Database, CheckCircle2, AlertOctagon, Cpu, Lock, Layers } from 'lucide-react';
export const HealthDashboard = ({ headSha, currentPhase }) => {
    const metrics = [
        { label: 'Current Active Phase', value: `Phase-${currentPhase}`, status: 'ACTIVE', color: 'text-cyan-400', icon: Cpu },
        { label: 'Repository Integrity', value: '100% Verified', status: 'PASS', color: 'text-emerald-400', icon: Database },
        { label: 'Authority Boundary Integrity', value: 'Ring0 / Ring3 Bounded', status: 'PASS', color: 'text-emerald-400', icon: ShieldCheck },
        { label: 'Evidence Binding Ratio', value: 'Exact-Subject SHA Bound', status: 'PASS', color: 'text-indigo-400', icon: Lock },
        { label: 'Syscall ABI Status', value: 'FROZEN (100% Intact)', status: 'FROZEN', color: 'text-emerald-400', icon: CheckCircle2 },
        { label: 'Critical Drift Violations', value: '0 Critical Violations', status: 'CLEAN', color: 'text-emerald-400', icon: AlertOctagon },
    ];
    return (_jsxs("div", { className: "p-6 max-w-7xl mx-auto space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-xl font-bold text-slate-100 flex items-center space-x-2", children: [_jsx(Activity, { className: "h-5 w-5 text-emerald-400" }), _jsx("span", { children: "Architecture Health & Trust Dashboard" })] }), _jsx("p", { className: "text-xs text-slate-400 mt-1", children: "Real-time single-pane evaluation of AykenOS technical integrity, contract freeze status, and governance health score." })] }), _jsx("div", { className: "flex items-center space-x-3", children: _jsxs("div", { className: "flex items-center space-x-2 bg-emerald-500/10 px-4 py-2 rounded-xl border border-emerald-500/30 font-mono text-xs text-emerald-400 font-bold", children: [_jsx(CheckCircle2, { className: "h-4 w-4 text-emerald-400" }), _jsx("span", { children: "Overall Trust Score: 98 / 100 (EXCELLENT)" })] }) })] }), _jsx("div", { className: "grid grid-cols-3 gap-6", children: metrics.map((m, idx) => {
                    const Icon = m.icon;
                    return (_jsxs("div", { className: "glass-panel p-5 border-slate-800 space-y-3 hover:border-slate-700 transition-all", children: [_jsxs("div", { className: "flex items-center justify-between text-xs font-mono", children: [_jsx("span", { className: "text-slate-400", children: m.label }), _jsx(Icon, { className: `h-4 w-4 ${m.color}` })] }), _jsx("div", { className: `text-lg font-bold font-mono ${m.color}`, children: m.value }), _jsxs("div", { className: "flex items-center justify-between pt-2 border-t border-slate-900 text-[10px] font-mono text-slate-500", children: [_jsxs("span", { children: ["Status: ", _jsx("strong", { className: "text-slate-300", children: m.status })] }), _jsxs("span", { children: ["Verified vs SHA ", headSha.slice(0, 8)] })] })] }, idx));
                }) }), _jsxs("div", { className: "glass-panel p-6 border-cyan-500/30 space-y-4", children: [_jsx("h3", { className: "text-base font-bold text-slate-100", children: "AykenOS Architectural Substrate Health Summary" }), _jsxs("div", { className: "space-y-3 font-mono text-xs", children: [_jsxs("div", { className: "bg-slate-950 p-3.5 rounded-lg border border-slate-800 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-2 text-slate-200", children: [_jsx(Layers, { className: "h-4 w-4 text-cyan-400" }), _jsx("span", { children: "Substrate Mechanism vs Policy Separation" })] }), _jsx("span", { className: "text-emerald-400 font-bold", children: "VERIFIED (100% Compliant)" })] }), _jsxs("div", { className: "bg-slate-950 p-3.5 rounded-lg border border-slate-800 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-2 text-slate-200", children: [_jsx(Lock, { className: "h-4 w-4 text-indigo-400" }), _jsx("span", { children: "Phase-24 Exact-Subject Evidence Planning" })] }), _jsx("span", { className: "text-emerald-400 font-bold", children: "RATIFIED & ACTIVE" })] }), _jsxs("div", { className: "bg-slate-950 p-3.5 rounded-lg border border-slate-800 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-2 text-slate-200", children: [_jsx(ShieldCheck, { className: "h-4 w-4 text-amber-400" }), _jsx("span", { children: "Unratified Code Authority Grant Invariant" })] }), _jsx("span", { className: "text-emerald-400 font-bold", children: "INVARIANT ENFORCED (grantsNewAuthority = false)" })] })] })] })] }));
};
//# sourceMappingURL=HealthDashboard.js.map