import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Flag, AlertTriangle, FileText, Lock } from 'lucide-react';
import { AYKENOS_PHASE_CATALOG } from '@ayatlas/authority-resolver';
export const PhaseExplorer = ({ currentPhase, headSha }) => {
    const [selectedPhase, setSelectedPhase] = useState(AYKENOS_PHASE_CATALOG.find((p) => p.phase === currentPhase) || AYKENOS_PHASE_CATALOG[AYKENOS_PHASE_CATALOG.length - 1]);
    const phase24Records = [
        { name: '1. Pointer Transition Record', path: 'docs/phase24-pointer-transition.md', desc: 'Initial phase transition entry.' },
        { name: '2. Governance Overview Record', path: 'docs/phase24-governance-overview.md', desc: 'System governance principles for Phase-24.' },
        { name: '3. Initial Governance Boundary Record', path: 'docs/phase24-initial-boundary.md', desc: 'Strict boundary specification.' },
        { name: '4. Exact-Subject Evidence Expectation Record', path: 'docs/phase24-exact-subject-expectations.md', desc: 'Exact SHA expectation rules.' },
        { name: '5. Objective, Scope and Sequencing Record', path: 'docs/phase24-objective-scope.md', desc: 'Sequence and roadmap definition.' },
        { name: '6. Accepted-Evidence Boundary Planning Record', path: 'docs/phase24-accepted-evidence-planning.md', desc: 'Accepted evidence boundary specs.' },
        { name: '7. Precision Correction Record (P2)', path: 'docs/phase24-p2-precision-correction.md', desc: 'P2 clarification: No downstream authority creation.' },
    ];
    return (_jsxs("div", { className: "p-6 max-w-7xl mx-auto space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-xl font-bold text-slate-100 flex items-center space-x-2", children: [_jsx(Flag, { className: "h-5 w-5 text-cyan-400" }), _jsx("span", { children: "AykenOS Phase & Governance Explorer" })] }), _jsx("p", { className: "text-xs text-slate-400 mt-1", children: "Tracking phase progression from Phase-0 through Phase-24 accepted-evidence planning and exact-subject binding." })] }), _jsxs("div", { className: "flex items-center space-x-2 bg-slate-900 p-2 rounded-xl border border-slate-800 text-xs font-mono", children: [_jsx("span", { className: "text-slate-400", children: "Current Phase:" }), _jsxs("span", { className: "text-cyan-400 font-bold px-2 py-0.5 rounded bg-cyan-500/10 border border-cyan-500/30", children: ["Phase-", currentPhase, " (ACTIVE)"] })] })] }), _jsx("div", { className: "grid grid-cols-5 gap-3", children: AYKENOS_PHASE_CATALOG.map((p) => {
                    const isSelected = selectedPhase.phase === p.phase;
                    const isActive = p.status === 'ACTIVE';
                    return (_jsxs("div", { onClick: () => setSelectedPhase(p), className: `glass-panel p-4 cursor-pointer transition-all duration-200 relative ${isSelected
                            ? 'border-cyan-500/60 bg-slate-900/90 shadow-cyan-500/10'
                            : 'hover:border-slate-700 opacity-80'}`, children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("span", { className: "text-sm font-bold text-slate-100", children: ["Phase-", p.phase] }), isActive ? (_jsx("span", { className: "text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 font-semibold", children: "ACTIVE" })) : (_jsx("span", { className: "text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/30", children: "CLOSED" }))] }), _jsx("div", { className: "text-xs text-slate-300 font-medium line-clamp-2", children: p.title })] }, p.phase));
                }) }), _jsxs("div", { className: "grid grid-cols-3 gap-6", children: [_jsx("div", { className: "col-span-2 space-y-6", children: _jsxs("div", { className: "glass-panel p-6 border-cyan-500/30 space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-slate-800 pb-3", children: [_jsxs("div", { children: [_jsx("span", { className: "text-xs font-mono text-cyan-400 uppercase tracking-wider font-semibold", children: "Phase Specification" }), _jsx("h3", { className: "text-lg font-bold text-slate-100", children: selectedPhase.title })] }), _jsx("span", { className: `text-xs font-mono px-3 py-1 rounded-full font-semibold ${selectedPhase.status === 'ACTIVE'
                                                ? 'bg-cyan-500/10 text-cyan-400 border border-cyan-500/30'
                                                : 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'}`, children: selectedPhase.status })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider mb-1", children: "Objective" }), _jsx("p", { className: "text-xs text-slate-300 bg-slate-950/60 p-3 rounded-lg border border-slate-800", children: selectedPhase.objective })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-xs font-bold text-slate-300 uppercase tracking-wider mb-1", children: "Authorized Scope" }), _jsx("p", { className: "text-xs text-slate-300 bg-slate-950/60 p-3 rounded-lg border border-slate-800", children: selectedPhase.scope })] }), _jsxs("div", { children: [_jsxs("h4", { className: "text-xs font-bold text-rose-400 uppercase tracking-wider mb-2 flex items-center space-x-1", children: [_jsx(AlertTriangle, { className: "h-3.5 w-3.5 text-rose-400" }), _jsxs("span", { children: ["Explicitly Unauthorized Scope in Phase-", selectedPhase.phase] })] }), _jsx("div", { className: "grid grid-cols-2 gap-2", children: selectedPhase.unauthorizedScope.map((item, idx) => (_jsxs("div", { className: "text-xs font-mono text-rose-300 bg-rose-500/10 p-2 rounded border border-rose-500/20 flex items-center space-x-1.5", children: [_jsx(Lock, { className: "h-3 w-3 text-rose-400 flex-shrink-0" }), _jsx("span", { children: item })] }, idx))) })] })] }) }), _jsx("div", { className: "space-y-4", children: _jsxs("div", { className: "glass-panel p-5 border-slate-800 space-y-3", children: [_jsxs("h4", { className: "text-xs font-bold text-slate-200 uppercase tracking-wider flex items-center space-x-1.5", children: [_jsx(FileText, { className: "h-4 w-4 text-cyan-400" }), _jsx("span", { children: "Phase-24 Decision Records" })] }), _jsx("p", { className: "text-[11px] text-slate-400 leading-relaxed", children: "Chronological decision sequence established in main repository:" }), _jsx("div", { className: "space-y-2", children: phase24Records.map((rec, idx) => (_jsxs("div", { className: "bg-slate-950/80 p-2.5 rounded-lg border border-slate-800 text-xs font-mono space-y-1 hover:border-cyan-500/40 transition-colors", children: [_jsx("div", { className: "text-cyan-300 font-semibold", children: rec.name }), _jsx("div", { className: "text-[10px] text-slate-500", children: rec.path })] }, idx))) })] }) })] })] }));
};
//# sourceMappingURL=PhaseExplorer.js.map